### ISSUE TITLE
TypeError: getattr(): attribute name must be string

### ISSUE THREAD

**Issue by FHL1998** [artidoro/qlora#129]
Traceback (most recent call last):
  File "qlora.py", line 791, in <module>
    train()
  File "qlora.py", line 636, in train
    tokenizer = AutoTokenizer.from_pretrained(
  File "/opt/conda/envs/env/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 635, in from_pretrained
    tokenizer_class = tokenizer_class_from_name(tokenizer_class_name)
  File "/opt/conda/envs/env/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 395, in tokenizer_class_from_name
    return getattr(module, class_name)
TypeError: getattr(): attribute name must be string

**Comment by FHL1998** [comment]
Someone says it is the issue related to diffusers version, anynoe know the correct version of the package?

**Comment by achsvg** [comment]
I had the same error. The Llama tokenizer requires `sentencepiece` to be installed. Try again after `pip install sentencepiece`.

**Comment by FHL1998** [comment]
>

**Comment by FHL1998** [comment]
> 

Thx! I get rid of the issue now.
