### ISSUE TITLE
finetune.py 65b on A6000 48GB crashes with OOM

### ISSUE THREAD

**Issue by disarmyouwitha** [artidoro/qlora#17]
```
python qlora.py \
    --model_name_or_path /home/nap/llm_models/llamaOG-65B-hf/ \
    --output_dir ./output \
    --dataset alpaca \
    --do_train True \
    --do_eval True \
    --do_mmlu_eval True \
    --source_max_len 384 \
    --target_max_len 128 \
    --per_device_train_batch_size 4 \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --logging_steps 10 \
    --max_steps 10000 \
    --save_strategy steps \
    --data_seed 42 \
    --save_steps 1000 \
    --save_total_limit 40 \
    --evaluation_strategy steps \
    --eval_dataset_size 1024 \
    --max_eval_samples 1000 \
    --eval_steps 1000 \
    --optim paged_adamw_32bit \
    --learning_rate 0.0001 \
```
    
CUDA_VISIBLE_DEVICES=1 ./finetune.sh

**error:**
```
  File "/home/nap/Documents/githubs/qlora/.qlora/lib/python3.11/site-packages/bitsandbytes/autograd/_functions.py", line 512, in forward
    output = torch.nn.functional.linear(A, F.dequantize_fp4(B, state).to(A.dtype).t(), bias)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 688.00 MiB (GPU 0; 47.54 GiB total capacity; 45.09 GiB already allocated; 79.12 MiB free; 46.45 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
  0%|                                                                                                                                 | 0/10000 [00:18<?, ?it/s] 
  ```

**Do I need to change the batch_size or something? Thanks!**

**Comment by Qubitium** [comment]
Try:

1. do_mmlu_eval = False
2. per_device_train_batch_size = 2

**Comment by disarmyouwitha** [comment]
> Try:
> 
> 1. do_mmlu_eval = False
> 2. per_device_train_batch_size = 2

**Updated:**
```
python qlora.py \
    --model_name_or_path /home/nap/llm_models/llamaOG-65B-hf/ \
    --output_dir ./output \
    --dataset alpaca \
    --do_train True \
    --do_eval True \
    --do_mmlu_eval False \
    --source_max_len 384 \
    --target_max_len 128 \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 4 \
    --logging_steps 10 \
    --max_steps 10000 \
    --save_strategy steps \
    --data_seed 42 \
    --save_steps 1000 \
    --save_total_limit 40 \
    --evaluation_strategy steps \
    --eval_dataset_size 1024 \
    --max_eval_samples 1000 \
    --eval_steps 1000 \
    --optim paged_adamw_32bit \
    --learning_rate 0.0001 \
    #--per_device_train_batch_size 4 \
```

**Error:**
```
Traceback (most recent call last):
  File "/home/nap/Documents/githubs/qlora/qlora.py", line 758, in <module>
    train()
  File "/home/nap/Documents/githubs/qlora/qlora.py", line 720, in train
    train_result = trainer.train(resume_from_checkpoint=checkpoint_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nap/Documents/githubs/qlora/.qlora/lib/python3.11/site-packages/transformers/trainer.py", line 1696, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/nap/Documents/githubs/qlora/.qlora/lib/python3.11/site-packages/transformers/trainer.py", line 1972, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nap/Documents/githubs/qlora/.qlora/lib/python3.11/site-packages/transformers/trainer.py", line 2804, in training_step
    loss.backward()
  File "/home/nap/Documents/githubs/qlora/.qlora/lib/python3.11/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/nap/Documents/githubs/qlora/.qlora/lib/python3.11/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1002.00 MiB (GPU 0; 47.54 GiB total capacity; 44.22 GiB already allocated; 967.12 MiB free; 45.58 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
  0%|
```

**Anything else I should try? Thanks!**

**Comment by USBhost** [comment]
per_device_train_batch_size 1


then you will be able to.

**Comment by OCEANOUXIN** [comment]
> > per_device_train_batch_size 1
> > then you will be able to.然后你就能。
> 
> Seems obvious now =] I was able to start training this way, Thanks!现在看来很明显 =] 我能够以这种方式开始训练了，谢谢！

Hi, what the performance of the results?
