### ISSUE TITLE
OverflowError: out of range integral type conversion attempted while running python qlora.py

### ISSUE THREAD

**Issue by amdnsr** [artidoro/qlora#18]
`python qlora.py --model_name_or_path decapoda-research/llama-13b-hf`

(I have updated the tokenizer_config.json and config.json as per the various discussions [here](https://huggingface.co/decapoda-research/llama-13b-hf/discussions/)
`tokenizer_class`: `LlamaTokenizer` and `architectures`: `LlamaForCausalLM`)

==================================================================================

adding LoRA modules...
trainable params: 125173760.0 || all params: 6922327040 || trainable: 1.8082612866554193
loaded model

Using pad_token, but it is not set yet.
Traceback (most recent call last):
  File "qlora.py", line 758, in <module>
    train()
  File "qlora.py", line 620, in train
    "unk_token": tokenizer.convert_ids_to_tokens(model.config.pad_token_id),
  File "/home/envs/qlora_env/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 307, in convert_ids_to_tokens
    return self._tokenizer.id_to_token(ids)
OverflowError: out of range integral type conversion attempted

**Comment by amdnsr** [comment]
Running of Tesla V100 32GB GPU

**Comment by LIO-H-ZEN** [comment]
same issue

**Comment by Qubitium** [comment]
Please check if this pr fixes your issue. The pr was designed to fix something else but will also bypass token conversion if tokenizer already contains the special tokens.

https://github.com/artidoro/qlora/pull/20

**Comment by ricksun2023** [comment]
same issue

**Comment by LIO-H-ZEN** [comment]
> > Please check if this pr fixes your issue. The pr was designed to fix something else but will also bypass token conversion if tokenizer already contains the special tokens.
> > #20
> 
> this is solve my issue but I am getting maximum recursion depth error now.
> 
> File "/home/atilla/miniconda3/envs/qlora/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 257, in _convert_token_to_id_with_added_voc     return self.unk_token_id   File "/home/atilla/miniconda3/envs/qlora/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1142, in unk_token_id     return self.convert_tokens_to_ids(self.unk_token)   File "/home/atilla/miniconda3/envs/qlora/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 250, in convert_tokens_to_ids     return self._convert_token_to_id_with_added_voc(tokens)   File "/home/atilla/miniconda3/envs/qlora/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 257, in _convert_token_to_id_with_added_voc     return self.unk_token_id   File "/home/atilla/miniconda3/envs/qlora/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1142, in unk_token_id     return self.convert_tokens_to_ids(self.unk_token)   File "/home/atilla/miniconda3/envs/qlora/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 250, in convert_tokens_to_ids     return self._convert_token_to_id_with_added_voc(tokens)   File "/home/atilla/miniconda3/envs/qlora/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 257, in _convert_token_to_id_with_added_voc     return self.unk_token_id   File "/home/atilla/miniconda3/envs/qlora/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1142, in unk_token_id     return self.convert_tokens_to_ids(self.unk_token)   File "/home/atilla/miniconda3/envs/qlora/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 250, in convert_tokens_to_ids     return self._convert_token_to_id_with_added_voc(tokens)   File "/home/atilla/miniconda3/envs/qlora/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 257, in _convert_token_to_id_with_added_voc     return self.unk_token_id   File "/home/atilla/miniconda3/envs/qlora/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1142, in unk_token_id     return self.convert_tokens_to_ids(self.unk_token) RecursionError: maximum recursion depth exceeded

same...

**Comment by atillabasaran** [comment]
> same issue
> 
> **update**
> 
> Change model.config.pad_token_id to 0 should fix this problem but may harm to training.
> 
> ```python
>         tokenizer.add_special_tokens(
>             {
>                 "eos_token": tokenizer.convert_ids_to_tokens(model.config.eos_token_id),
>                 "bos_token": tokenizer.convert_ids_to_tokens(model.config.bos_token_id),
>                 "unk_token": tokenizer.convert_ids_to_tokens(0),
>             }
>         )
> ```

I wonder what exactly does this change provide?

**Comment by mofanv** [comment]
same issue

**Comment by hemangjoshi37a** [comment]
@amdnsr,

Based on the error message you shared, it appears that there is an "OverflowError: out of range integral type conversion attempted" when converting token IDs during tokenization. To address this issue, we recommend the following solution:

1. Update your code as follows:

```python
from transformers import LlamaTokenizer

tokenizer = LlamaTokenizer.from_pretrained("decapoda-research/llama-13b-hf")
tokenizer.add_special_tokens({"pad_token": "[PAD]"})

# Rest of your code...
```

By using the `LlamaTokenizer` from the `transformers` library and adding the `[PAD]` token as a special token, you can resolve the "out of range integral type conversion" error.

Best regards,
@hemangjoshi37a

**Comment by saxenarohit** [comment]
Setting pad_token_id in the model config worked for me.

For example for vicuna
`model.config.pad_token_id = tokenizer.eos_token_id  `
