### ISSUE TITLE
TypeError: 'dict_values' object is not subscriptable

### ISSUE THREAD

**Issue by adaaaaaa** [artidoro/qlora#191]
`python qlora.py --model_name_or_path ../text-generation-webui/models/lmsys_vicuna-7b-v1.3/                                                                                           ─╯

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/nano/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
CUDA SETUP: CUDA runtime path found: /opt/cuda/targets/x86_64-linux/lib/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /home/nano/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
[2023-06-28 13:04:44,410] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
loading base model ../text-generation-webui/models/lmsys_vicuna-7b-v1.3/...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:35<00:00, 17.94s/it]
Traceback (most recent call last):
  File "/data/qlora/qlora.py", line 807, in <module>
    train()
  File "/data/qlora/qlora.py", line 643, in train
    model = get_accelerate_model(args, checkpoint_dir)
  File "/data/qlora/qlora.py", line 280, in get_accelerate_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/nano/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 484, in from_pretrained
    return model_class.from_pretrained(
  File "/home/nano/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2937, in from_pretrained
    dispatch_model(model, **kwargs)
  File "/home/nano/.local/lib/python3.10/site-packages/accelerate/big_modeling.py", line 389, in dispatch_model
    device = device_map.values()[0]
TypeError: 'dict_values' object is not subscriptable
`
can the "vicuna-7b-v1.3" model using qlora?

**Comment by lyogavin** [comment]
it looks like accelerate's recent [change](https://github.com/huggingface/accelerate/commit/5ea7c81277cde468a454ea5bffcb14b7e2d270f6) is breaking something.

Probably we should not always install pacakges from head? 


change requirements.txt  to:
`accelerate @ git+https://github.com/huggingface/accelerate.git@v0.20.3`
