### ISSUE TITLE
Finetuning the Llama-2-70b-chat-hf

### ISSUE THREAD

**Issue by SoumitriKolavennu** [artidoro/qlora#226]
Hi,
Is it possible to finetune the 70b-chat-hf version of Llama-2? This version uses grouped query attention unlike the 7b and 13b versions of llama-2. We are planning to test it on 8xA100 cluster.

**Comment by artidoro** [comment]
I haven't tried the chat version, but I successfully finetuned the 70B model on a single A40 48Gb GPU. 

If you have more GPUs and the models fits on a single GPU you should also use DDP to parallelize across GPUs. Check the discussion on DDP PR.

**Comment by SoumitriKolavennu** [comment]
So I did try finetuning the llama-2-70b-hf model with qlora and it worked fine. 

However exact same script and exact same alpaca style instruction set with llama-2-70b-chat-hf fails to train .. 

Can you please try and see if you can finetune chat-hf model?

**Comment by SoumitriKolavennu** [comment]
This is the error I get with llama-2-70b-chat-hf:

  0%|                                                                                              | 0/100 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/ds_nlp_air/users/Soumitri/LLM/qlora/qlora.py", line 812, in <module>
    train()
  File "/ds_nlp_air/users/Soumitri/LLM/qlora/qlora.py", line 774, in train
    train_result = trainer.train()
  File "<MY_DIR> python3.9/site-packages/transformers/trainer.py", line 1532, in train
    return inner_training_loop(
  File "<MY_DIR> python3.9/site-packages/transformers/trainer.py", line 1805, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "<MY_DIR> python3.9/site-packages/transformers/trainer.py", line 2647, in training_step
    loss = self.compute_loss(model, inputs)
  File "<MY_DIR> python3.9/site-packages/transformers/trainer.py", line 2672, in compute_loss
    outputs = model(**inputs)
  File "<MY_DIR> python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "<MY_DIR> python3.9/site-packages/accelerate/utils/operations.py", line 632, inforward
    return model_forward(*args, **kwargs)
  File "<MY_DIR> python3.9/site-packages/accelerate/utils/operations.py", line 620, in__call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "<MY_DIR> python3.9/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "<MY_DIR> python3.9/site-packages/peft/peft_model.py", line 785, in forward
    return self.base_model(
  File "<MY_DIR> python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "<MY_DIR> python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "<MY_DIR> python3.9/site-packages/transformers/models/llama/modeling_llama.py",line 810, in forward
    outputs = self.model(
  File "<MY_DIR> python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "<MY_DIR> python3.9/site-packages/transformers/models/llama/modeling_llama.py",line 690, in forward
    layer_outputs = torch.utils.checkpoint.checkpoint(
  File "<MY_DIR> python3.9/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "<MY_DIR> python3.9/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "<MY_DIR> python3.9/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "<MY_DIR> python3.9/site-packages/transformers/models/llama/modeling_llama.py",line 686, in custom_forward
    return module(*inputs, output_attentions, None)
  File "<MY_DIR> python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "<MY_DIR> python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "<MY_DIR> python3.9/site-packages/transformers/models/llama/modeling_llama.py",line 413, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "<MY_DIR> python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "<MY_DIR> python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "<MY_DIR> python3.9/site-packages/transformers/models/llama/modeling_llama.py",line 300, in forward
    query_states = [F.linear(hidden_states, query_slices[i]) for i in range(self.config.pretraining_tp)]
  File "<MY_DIR> python3.9/site-packages/transformers/models/llama/modeling_llama.py",line 300, in <listcomp>
    query_states = [F.linear(hidden_states, query_slices[i]) for i in range(self.config.pretraining_tp)]
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1076x8192 and 1x1024)
  0%|                                                                                              | 0/100 [00:00<?, ?it/s]
