### ISSUE TITLE
undefined symbol: cquantize_blockwise_fp16_fp4

### ISSUE THREAD

**Issue by DamonGuzman** [artidoro/qlora#31]
AttributeError                            Traceback (most recent call last)
Cell In[6], line 1
----> 1 model = LlamaForCausalLM.from_pretrained(".[./hf_llama](https://vscode-remote+ssh-002dremote-002bvocal-002dserver-002d1.vscode-resource.vscode-cdn.net/home/server/vocal/models/hf_llama/hf_llama)", device_map="auto", torch_dtype=torch.float16, load_in_4bit=True )

File [~/anaconda3/envs/qlora/lib/python3.11/site-packages/transformers/modeling_utils.py:2829](https://vscode-remote+ssh-002dremote-002bvocal-002dserver-002d1.vscode-resource.vscode-cdn.net/home/server/vocal/models/hf_llama/~/anaconda3/envs/qlora/lib/python3.11/site-packages/transformers/modeling_utils.py:2829), in PreTrainedModel.from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
   2819     if dtype_orig is not None:
   2820         torch.set_default_dtype(dtype_orig)
   2822     (
   2823         model,
   2824         missing_keys,
   2825         unexpected_keys,
   2826         mismatched_keys,
   2827         offload_index,
   2828         error_msgs,
-> 2829     ) = cls._load_pretrained_model(
   2830         model,
   2831         state_dict,
   2832         loaded_state_dict_keys,  # XXX: rename?
   2833         resolved_archive_file,
   2834         pretrained_model_name_or_path,
   2835         ignore_mismatched_sizes=ignore_mismatched_sizes,
   2836         sharded_metadata=sharded_metadata,
   2837         _fast_init=_fast_init,
   2838         low_cpu_mem_usage=low_cpu_mem_usage,
...
--> 394     func = self._FuncPtr((name_or_ordinal, self))
    395     if not isinstance(name_or_ordinal, int):
    396         func.__name__ = name_or_ordinal

AttributeError: /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cquantize_blockwise_fp16_fp4

**Comment by DamonGuzman** [comment]
nd submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/server/anaconda3/envs/qlora did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
  warn(msg)
/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
loading base model EleutherAI/pythia-12b...
Downloading (…)l-00001-of-00003.bin: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9.81G/9.81G [03:57<00:00, 41.3MB/s]
Downloading (…)l-00002-of-00003.bin: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9.93G/9.93G [03:44<00:00, 44.3MB/s]
Downloading (…)l-00003-of-00003.bin: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.11G/4.11G [01:32<00:00, 44.5MB/s]
Downloading shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [09:20<00:00, 186.80s/it]
Loading checkpoint shards:   0%|                                                                                                                                                                                | 0/3 [00:09<?, ?it/s]
Traceback (most recent call last):
  File "/home/server/vocal/huggingface/qlora/qlora.py", line 758, in <module>
    train()
  File "/home/server/vocal/huggingface/qlora/qlora.py", line 590, in train
    model = get_accelerate_model(args, checkpoint_dir)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/server/vocal/huggingface/qlora/qlora.py", line 263, in get_accelerate_model
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 472, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2829, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3172, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/transformers/modeling_utils.py", line 718, in _load_state_dict_into_meta_model
    set_module_quantized_tensor_to_device(
  File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/transformers/utils/bitsandbytes.py", line 88, in set_module_quantized_tensor_to_device
    new_value = bnb.nn.Params4bit(new_value, requires_grad=False, **kwargs).to(device)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/nn/modules.py", line 176, in to
    return self.cuda(device)
           ^^^^^^^^^^^^^^^^^
  File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/nn/modules.py", line 154, in cuda
    w_4bit, quant_state = bnb.functional.quantize_4bit(w, blocksize=self.blocksize, compress_statistics=self.compress_statistics, quant_type=self.quant_type)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/functional.py", line 776, in quantize_4bit
    lib.cquantize_blockwise_fp16_nf4(get_ptr(None), get_ptr(A), get_ptr(absmax), get_ptr(out), ct.c_int32(blocksize), ct.c_int(n))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/server/anaconda3/envs/qlora/lib/python3.11/ctypes/__init__.py", line 389, in __getattr__
    func = self.__getitem__(name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/server/anaconda3/envs/qlora/lib/python3.11/ctypes/__init__.py", line 394, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cquantize_blockwise_fp16_nf4

**Comment by Qubitium** [comment]
@DamonGuzman  Looks like you did not build bitsandbytes with gpu support? It is loading the cpu and not cuda version. 

`UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.`

`CUDA SETUP: Loading binary /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so...`

**Comment by DamonGuzman** [comment]
> @DamonGuzman Looks like you did not build bitsandbytes with gpu support? It is loading the cpu and not cuda version.
> 
> `UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.`
> 
> `CUDA SETUP: Loading binary /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so...`


That was actually really close to the problem I was having! I had created a new conda environment and needed to install cuda toolkit in that new environment. I always assumed cuda tool kit was a system-wide package but that doesn't seem to be the case.

**Comment by muelletm** [comment]
Just in case this is helpful for someone:

If you get this with docker make sure to use an image with cuda toolkit installed, e.g.:

`pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel`

**Comment by Lauorie** [comment]
> # nd submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
> 
> bin /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable. warn("The installed version of bitsandbytes was compiled without GPU support. " /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32 /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/server/anaconda3/envs/qlora did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths... warn(msg) CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths... /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')} warn(msg) /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)! warn(msg) CUDA SETUP: Highest compute capability among GPUs detected: 8.6 CUDA SETUP: Detected CUDA version 117 CUDA SETUP: Loading binary /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so... loading base model EleutherAI/pythia-12b... Downloading (…)l-00001-of-00003.bin: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9.81G/9.81G [03:57<00:00, 41.3MB/s] Downloading (…)l-00002-of-00003.bin: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9.93G/9.93G [03:44<00:00, 44.3MB/s] Downloading (…)l-00003-of-00003.bin: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.11G/4.11G [01:32<00:00, 44.5MB/s] Downloading shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [09:20<00:00, 186.80s/it] Loading checkpoint shards: 0%| | 0/3 [00:09<?, ?it/s] Traceback (most recent call last): File "/home/server/vocal/huggingface/qlora/qlora.py", line 758, in train() File "/home/server/vocal/huggingface/qlora/qlora.py", line 590, in train model = get_accelerate_model(args, checkpoint_dir) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/server/vocal/huggingface/qlora/qlora.py", line 263, in get_accelerate_model model = AutoModelForCausalLM.from_pretrained( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 472, in from_pretrained return model_class.from_pretrained( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2829, in from_pretrained ) = cls._load_pretrained_model( ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3172, in _load_pretrained_model new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/transformers/modeling_utils.py", line 718, in _load_state_dict_into_meta_model set_module_quantized_tensor_to_device( File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/transformers/utils/bitsandbytes.py", line 88, in set_module_quantized_tensor_to_device new_value = bnb.nn.Params4bit(new_value, requires_grad=False, **kwargs).to(device) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/nn/modules.py", line 176, in to return self.cuda(device) ^^^^^^^^^^^^^^^^^ File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/nn/modules.py", line 154, in cuda w_4bit, quant_state = bnb.functional.quantize_4bit(w, blocksize=self.blocksize, compress_statistics=self.compress_statistics, quant_type=self.quant_type) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/functional.py", line 776, in quantize_4bit lib.cquantize_blockwise_fp16_nf4(get_ptr(None), get_ptr(A), get_ptr(absmax), get_ptr(out), ct.c_int32(blocksize), ct.c_int(n)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/server/anaconda3/envs/qlora/lib/python3.11/ctypes/**init**.py", line 389, in **getattr** func = self.**getitem**(name) ^^^^^^^^^^^^^^^^^^^^^^ File "/home/server/anaconda3/envs/qlora/lib/python3.11/ctypes/**init**.py", line 394, in **getitem** func = self._FuncPtr((name_or_ordinal, self)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cquantize_blockwise_fp16_nf4

I solved this by "conda install cudatoolkit=11.7 -y".

**Comment by DanielLeung222** [comment]
For me, I just replace libbitsandbytes_cpu.so to be libbitsandbytes_cuda117.so, which 117 is the cuda vision that I am now using.

You may refer to this link: https://github.com/TimDettmers/bitsandbytes/issues/156#issuecomment-1474056975

**Comment by harigovind511** [comment]
I faced the same issue today, turns it I had a version conflict between Cuda and PyTorch. A fresh install of Cuda and PyTorch did the trick for me.

**Comment by chensaics** [comment]
you can try this method:

`cd [your bitsandbytes env path]`
eg. :   **cd /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/**
you can copy the path from your terminal

then:
`cp libbitsandbytes_cuda117.so libbitsandbytes_cpu.so`

ps : "CUDA version 117" is your cuda version, so here is " libbitsandbytes_cuda117.so"

**Comment by OlympixJack** [comment]
I've encountered an issue that seems to be unrelated with infra or python packages. It had a runtime error due to matrix dimensions (see below). Any suggestions on how to fix are appreciated.

```
Traceback (most recent call last):
  File "finetune.py", line 209, in <module>
    trainer.train()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1938, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers/trainer.py", line 2759, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers/trainer.py", line 2784, in compute_loss
    outputs = model(**inputs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/peft/peft_model.py", line 678, in forward
    return self.base_model(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/ubuntu/.cache/huggingface/modules/transformers_modules/tiiuae/falcon-7b/2f5c3cd4eace6be6c0f12981f377fb35e5bf6ee5/modelling_RW.py", line 753, in forward
    transformer_outputs = self.transformer(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/ubuntu/.cache/huggingface/modules/transformers_modules/tiiuae/falcon-7b/2f5c3cd4eace6be6c0f12981f377fb35e5bf6ee5/modelling_RW.py", line 648, in forward
    outputs = block(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/ubuntu/.cache/huggingface/modules/transformers_modules/tiiuae/falcon-7b/2f5c3cd4eace6be6c0f12981f377fb35e5bf6ee5/modelling_RW.py", line 385, in forward
    attn_outputs = self.self_attention(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/ubuntu/.cache/huggingface/modules/transformers_modules/tiiuae/falcon-7b/2f5c3cd4eace6be6c0f12981f377fb35e5bf6ee5/modelling_RW.py", line 242, in forward
    fused_qkv = self.query_key_value(hidden_states)  # [batch_size, seq_length, 3 x hidden_size]
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/peft/tuners/lora.py", line 565, in forward
    result = F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (2048x4544 and 1x10614784)
```

**Comment by radaevm** [comment]
`cp libbitsandbytes_cuda117.so libbitsandbytes_cpu.so`

This method worked for me in WSL Ubuntu on Windows11. I installed anacoda3 and cuda118 special version for `WSL2`

FineTuning Vicuna-13B with QloRA works well on RTX4090

**Comment by wyxscir** [comment]
i solved it by repip the "bitsandbytes"

**Comment by snow-like-kk** [comment]
> > # nd submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
> > bin /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable. warn("The installed version of bitsandbytes was compiled without GPU support. " /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32 /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/server/anaconda3/envs/qlora did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths... warn(msg) CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths... /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')} warn(msg) /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)! warn(msg) CUDA SETUP: Highest compute capability among GPUs detected: 8.6 CUDA SETUP: Detected CUDA version 117 CUDA SETUP: Loading binary /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so... loading base model EleutherAI/pythia-12b... Downloading (…)l-00001-of-00003.bin: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9.81G/9.81G [03:57<00:00, 41.3MB/s] Downloading (…)l-00002-of-00003.bin: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9.93G/9.93G [03:44<00:00, 44.3MB/s] Downloading (…)l-00003-of-00003.bin: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.11G/4.11G [01:32<00:00, 44.5MB/s] Downloading shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [09:20<00:00, 186.80s/it] Loading checkpoint shards: 0%| | 0/3 [00:09<?, ?it/s] Traceback (most recent call last): File "/home/server/vocal/huggingface/qlora/qlora.py", line 758, in train() File "/home/server/vocal/huggingface/qlora/qlora.py", line 590, in train model = get_accelerate_model(args, checkpoint_dir) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/server/vocal/huggingface/qlora/qlora.py", line 263, in get_accelerate_model model = AutoModelForCausalLM.from_pretrained( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 472, in from_pretrained return model_class.from_pretrained( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2829, in from_pretrained ) = cls._load_pretrained_model( ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3172, in _load_pretrained_model new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/transformers/modeling_utils.py", line 718, in _load_state_dict_into_meta_model set_module_quantized_tensor_to_device( File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/transformers/utils/bitsandbytes.py", line 88, in set_module_quantized_tensor_to_device new_value = bnb.nn.Params4bit(new_value, requires_grad=False, **kwargs).to(device) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/nn/modules.py", line 176, in to return self.cuda(device) ^^^^^^^^^^^^^^^^^ File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/nn/modules.py", line 154, in cuda w_4bit, quant_state = bnb.functional.quantize_4bit(w, blocksize=self.blocksize, compress_statistics=self.compress_statistics, quant_type=self.quant_type) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/functional.py", line 776, in quantize_4bit lib.cquantize_blockwise_fp16_nf4(get_ptr(None), get_ptr(A), get_ptr(absmax), get_ptr(out), ct.c_int32(blocksize), ct.c_int(n)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/server/anaconda3/envs/qlora/lib/python3.11/ctypes/**init**.py", line 389, in **getattr** func = self.**getitem**(name) ^^^^^^^^^^^^^^^^^^^^^^ File "/home/server/anaconda3/envs/qlora/lib/python3.11/ctypes/**init**.py", line 394, in **getitem** func = self._FuncPtr((name_or_ordinal, self)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: /home/server/anaconda3/envs/qlora/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cquantize_blockwise_fp16_nf4
> 
> I solved this by "conda install cudatoolkit=11.7 -y".

thank you very much, i solved the same problems as well with this function
